services:
  - type: web
    name: miza
    runtime: php
    buildCommand: bash build.sh
    startCommand: vendor/bin/heroku-php-apache2 public/
    plan: free
    region: frankfurt
    buildFilter:
      paths:
        - composer.json
        - composer.lock
        - src/**/*.php
        - config/**/*
        - public/**/*
        - templates/**/*
    buildpack: heroku/php
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_DEBUG
        value: "0"
      - key: PHP_VERSION
        value: "8.1"
      - key: COMPOSER_VERSION
        value: "2"
    healthCheckPath: /
    autoDeploy: false
    disk:
      name: uploads
      mountPath: public/uploads
      sizeGB: 1 