# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    product_images_directory: '%kernel.project_dir%/public/uploads/products'
    upload_max_size: '10M'
    upload_tmp_dir: '%kernel.project_dir%/var/tmp'
    app.locales: [en, fr]
    paypal_client_id: '%env(PAYPAL_CLIENT_ID)%'
    paypal_client_secret: '%env(PAYPAL_CLIENT_SECRET)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Add the authentication success handler service
    App\Security\AuthenticationSuccessHandler:
        arguments:
            $urlGenerator: '@router'

    # Add the database exception listener
    App\EventListener\DatabaseExceptionListener:
        arguments:
            $urlGenerator: '@router'
            $environment: '%kernel.environment%'
        tags:
            - { name: kernel.event_subscriber }

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
